"""
Generation pipeline (Milestone 5).

Wires retrieval → grounded generation → source attribution.
Call ask(question) to get a grounded answer with sources.
"""

import os
from groq import Groq
from dotenv import load_dotenv
from embed import retrieve

load_dotenv()

GROQ_MODEL = "llama-3.3-70b-versatile"

# ── System prompt ──────────────────────────────────────────────────────────────
# Written as strict rules, not suggestions, so the model cannot wander off-context.
SYSTEM_PROMPT = """You are a syllabus assistant for Augsburg University students.
Students ask you questions about their course syllabi and you answer from the provided excerpts.

Rules you must follow without exception:
1. Answer ONLY using information that appears in the provided context below.
2. Do NOT use any outside knowledge, even if you are confident it is correct.
3. If the context does not contain enough information to answer the question, respond with exactly:
   "I don't have enough information about that in the provided syllabi."
4. Do not guess, infer, or fill in details that are not stated in the context.
5. Keep your answer concise and direct — one short paragraph is enough.
6. Do not mention phrases like "according to the context" or "based on the documents" — just answer naturally."""


def _build_context(chunks: list[dict]) -> str:
    """Format retrieved chunks into a numbered context block for the prompt."""
    parts = []
    for i, chunk in enumerate(chunks, 1):
        source = chunk["source"].replace(".pdf", "")
        parts.append(f"[{i}] Source: {source}\n{chunk['text']}")
    return "\n\n".join(parts)


def _dedupe_sources(chunks: list[dict]) -> list[str]:
    """Return unique source filenames in the order they first appeared."""
    seen = []
    for chunk in chunks:
        if chunk["source"] not in seen:
            seen.append(chunk["source"])
    return seen


def ask(question: str) -> dict:
    """
    End-to-end RAG call.

    Returns:
        {
            "answer":  str,        # grounded LLM response
            "sources": list[str],  # deduplicated source filenames (programmatic)
        }
    """
    # 1. Retrieve relevant chunks
    chunks = retrieve(question)

    if not chunks:
        return {
            "answer": "I don't have enough information about that in the provided syllabi.",
            "sources": [],
        }

    # 2. Build context string
    context = _build_context(chunks)

    # 3. Compose user message — context is injected here, not in the system prompt,
    #    so the grounding rules always frame the context no matter the question.
    user_message = f"""Context from course syllabi:
{context}

Question: {question}"""

    # 4. Call Groq
    client = Groq(api_key=os.environ["GROQ_API_KEY"])
    response = client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": user_message},
        ],
        temperature=0.0,   # deterministic — no creative additions
        max_tokens=512,
    )

    answer = response.choices[0].message.content.strip()

    # 5. Source attribution is programmatic — extracted from retrieval metadata,
    #    not generated by the LLM, so it is always accurate.
    sources = _dedupe_sources(chunks)

    return {"answer": answer, "sources": sources}


# ── CLI test ───────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    test_queries = [
        "What are the office hours for CSC 311?",
        "What happens if you submit a late assignment in CSC 311?",
        "What percentage of the DST 490 grade comes from the Data Visualization Project?",
    ]

    for query in test_queries:
        print(f"\nQ: {query}")
        result = ask(query)
        print(f"A: {result['answer']}")
        print(f"Sources: {', '.join(result['sources'])}")
        print("-" * 60)
